export declare function isDomIe8(target: any): target is HTMLElement;
export declare function isDomStandard(target: any): target is HTMLElement;
export declare const isDom: (target: any) => target is HTMLElement;
export declare function isElementOf(nodeName: string, el: any): boolean;
export declare function isSelectElement(el: HTMLElement): el is HTMLSelectElement;
export declare function isInputElement(el: HTMLElement): el is HTMLInputElement;
export declare function isTextAreaElement(el: HTMLElement): el is HTMLTextAreaElement;
export declare function isImgElement(el: HTMLElement): el is HTMLImageElement;
export declare function isDivElement(el: HTMLElement): el is HTMLDivElement;
export declare function isSpanElement(el: HTMLElement): el is HTMLSpanElement;
export declare function isUlElement(el: HTMLElement): el is HTMLUListElement;
